# Generated by Django 4.1.4 on 2024-07-21 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BoolInstans',
            new_name='BookInstans',
        ),
    ]
