# Generated by Django 4.1.4 on 2024-07-21 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_rename_boolinstans_bookinstans'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BookInstans',
            new_name='BookInstance',
        ),
    ]
